name: CI
on:
  workflow_dispatch:
  pull_request:
    branches: 
      [develop,workflow_dispatch] #develop向けのプルリクが作成されたときにジョブを実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #チェックアウトするアクション
      - name: Use NodeJS
        uses: actions/setup-node@v1 #特定バージョンのnodeを設定するアクション
        with:
          node-version: "12.x"
      - run: npm ci #dependencyのインストール
      - run: npx eslint . #コードフォーマットチェック
        env:
          CI: true #現在の環境がCI環境であることを仮定
